FROM node:18.17.1

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --omit=dev
COPY ./src ./src
RUN mkdir ./storage

# Install FFmpeg
RUN apt-get update && apt-get install -y ffmpeg

CMD npm start
